// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'crypto_coin_details.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CryptoCoinDetails _$CryptoCoinDetailsFromJson(Map<String, dynamic> json) =>
    CryptoCoinDetails(
      id: json['id'] as String,
      symbol: json['symbol'] as String,
      name: json['name'] as String,
      webSlug: json['web_slug'] as String?,
      blockTimeInMinutes: json['block_time_in_minutes'] as int,
      hashingAlgorithm: json['hashing_algorithm'] as String?,
      categories: (json['categories'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      previewListing: json['preview_listing'] as bool,
      localization:
          Localization.fromJson(json['localization'] as Map<String, dynamic>),
      description:
          Description.fromJson(json['description'] as Map<String, dynamic>),
      links: Links.fromJson(json['links'] as Map<String, dynamic>),
      image: Image.fromJson(json['image'] as Map<String, dynamic>),
      countryOrigin: json['country_origin'] as String?,
      genesisDate: json['genesis_date'] as String?,
      sentimentVotesUpPercentage:
          (json['sentiment_votes_up_percentage'] as num).toDouble(),
      sentimentVotesDownPercentage:
          (json['sentiment_votes_down_percentage'] as num).toDouble(),
      watchlistPortfolioUsers: json['watchlist_portfolio_users'] as int,
      marketCapRank: json['market_cap_rank'] as int?,
      coingeckoRank: (json['coingecko_rank'] as num?)?.toDouble(),
      coingeckoScore: (json['coingecko_score'] as num).toDouble(),
      developerScore: (json['developer_score'] as num).toDouble(),
      communityScore: (json['community_score'] as num).toDouble(),
      liquidityScore: (json['liquidity_score'] as num).toDouble(),
      publicInterestScore: (json['public_interest_score'] as num).toDouble(),
      statusUpdates: json['status_updates'] as List<dynamic>,
      lastUpdated: json['last_updated'] as String?,
      marketData:
          MarketData.fromJson(json['market_data'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$CryptoCoinDetailsToJson(CryptoCoinDetails instance) =>
    <String, dynamic>{
      'id': instance.id,
      'symbol': instance.symbol,
      'name': instance.name,
      'web_slug': instance.webSlug,
      'block_time_in_minutes': instance.blockTimeInMinutes,
      'hashing_algorithm': instance.hashingAlgorithm,
      'categories': instance.categories,
      'preview_listing': instance.previewListing,
      'localization': instance.localization.toJson(),
      'description': instance.description.toJson(),
      'links': instance.links.toJson(),
      'image': instance.image.toJson(),
      'country_origin': instance.countryOrigin,
      'genesis_date': instance.genesisDate,
      'sentiment_votes_up_percentage': instance.sentimentVotesUpPercentage,
      'sentiment_votes_down_percentage': instance.sentimentVotesDownPercentage,
      'watchlist_portfolio_users': instance.watchlistPortfolioUsers,
      'market_cap_rank': instance.marketCapRank,
      'coingecko_rank': instance.coingeckoRank,
      'coingecko_score': instance.coingeckoScore,
      'developer_score': instance.developerScore,
      'community_score': instance.communityScore,
      'liquidity_score': instance.liquidityScore,
      'public_interest_score': instance.publicInterestScore,
      'market_data': instance.marketData.toJson(),
      'status_updates': instance.statusUpdates,
      'last_updated': instance.lastUpdated,
    };

Localization _$LocalizationFromJson(Map<String, dynamic> json) => Localization(
      en: json['en'] as String,
      de: json['de'] as String,
    );

Map<String, dynamic> _$LocalizationToJson(Localization instance) =>
    <String, dynamic>{
      'en': instance.en,
      'de': instance.de,
    };

Description _$DescriptionFromJson(Map<String, dynamic> json) => Description(
      en: json['en'] as String,
      de: json['de'] as String,
    );

Map<String, dynamic> _$DescriptionToJson(Description instance) =>
    <String, dynamic>{
      'en': instance.en,
      'de': instance.de,
    };

Links _$LinksFromJson(Map<String, dynamic> json) => Links(
      homepage:
          (json['homepage'] as List<dynamic>).map((e) => e as String).toList(),
      blockchainSite: (json['blockchain_site'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      officialForumUrl: (json['official_forum_url'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      chatUrl:
          (json['chat_url'] as List<dynamic>).map((e) => e as String).toList(),
      announcementUrl: (json['announcement_url'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      twitterScreenName: json['twitter_screen_name'] as String,
      facebookUsername: json['facebook_username'] as String,
      telegramChannelIdentifier: json['telegram_channel_identifier'] as String,
      subredditUrl: json['subreddit_url'] as String,
      reposUrl: ReposUrl.fromJson(json['repos_url'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$LinksToJson(Links instance) => <String, dynamic>{
      'homepage': instance.homepage,
      'blockchain_site': instance.blockchainSite,
      'official_forum_url': instance.officialForumUrl,
      'chat_url': instance.chatUrl,
      'announcement_url': instance.announcementUrl,
      'twitter_screen_name': instance.twitterScreenName,
      'facebook_username': instance.facebookUsername,
      'telegram_channel_identifier': instance.telegramChannelIdentifier,
      'subreddit_url': instance.subredditUrl,
      'repos_url': instance.reposUrl.toJson(),
    };

ReposUrl _$ReposUrlFromJson(Map<String, dynamic> json) => ReposUrl(
      github:
          (json['github'] as List<dynamic>).map((e) => e as String).toList(),
      bitbucket: json['bitbucket'] as List<dynamic>,
    );

Map<String, dynamic> _$ReposUrlToJson(ReposUrl instance) => <String, dynamic>{
      'github': instance.github,
      'bitbucket': instance.bitbucket,
    };

Image _$ImageFromJson(Map<String, dynamic> json) => Image(
      thumb: json['thumb'] as String,
      small: json['small'] as String,
      large: json['large'] as String,
    );

Map<String, dynamic> _$ImageToJson(Image instance) => <String, dynamic>{
      'thumb': instance.thumb,
      'small': instance.small,
      'large': instance.large,
    };

MarketData _$MarketDataFromJson(Map<String, dynamic> json) => MarketData(
      currentPrice:
          CurrentPrice.fromJson(json['current_price'] as Map<String, dynamic>),
      ath: Ath.fromJson(json['ath'] as Map<String, dynamic>),
      athChangePercentage: AthChangePercentage.fromJson(
          json['ath_change_percentage'] as Map<String, dynamic>),
      marketCap: MarketCap.fromJson(json['market_cap'] as Map<String, dynamic>),
      marketCapRank: json['market_cap_rank'] as int,
      fullyDilutedValuation: FullyDilutedValuation.fromJson(
          json['fully_diluted_valuation'] as Map<String, dynamic>),
      totalVolume:
          TotalVolume.fromJson(json['total_volume'] as Map<String, dynamic>),
      priceChange24h: (json['price_change_24h'] as num).toDouble(),
      totalSupply: (json['total_supply'] as num?)?.toDouble(),
      maxSupply: (json['max_supply'] as num?)?.toDouble(),
      sparkLine7d:
          SparkLine7d.fromJson(json['sparkline_7d'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$MarketDataToJson(MarketData instance) =>
    <String, dynamic>{
      'current_price': instance.currentPrice.toJson(),
      'sparkline_7d': instance.sparkLine7d.toJson(),
      'ath': instance.ath.toJson(),
      'ath_change_percentage': instance.athChangePercentage.toJson(),
      'market_cap': instance.marketCap.toJson(),
      'market_cap_rank': instance.marketCapRank,
      'fully_diluted_valuation': instance.fullyDilutedValuation.toJson(),
      'total_volume': instance.totalVolume.toJson(),
      'price_change_24h': instance.priceChange24h,
      'total_supply': instance.totalSupply,
      'max_supply': instance.maxSupply,
    };

CurrentPrice _$CurrentPriceFromJson(Map<String, dynamic> json) => CurrentPrice(
      bnb: (json['bnb'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
    );

Map<String, dynamic> _$CurrentPriceToJson(CurrentPrice instance) =>
    <String, dynamic>{
      'bnb': instance.bnb,
      'btc': instance.btc,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'jpy': instance.jpy,
      'uah': instance.uah,
      'usd': instance.usd,
    };

Ath _$AthFromJson(Map<String, dynamic> json) => Ath(
      aed: (json['aed'] as num?)?.toDouble(),
      ars: (json['ars'] as num?)?.toDouble(),
      aud: (json['aud'] as num?)?.toDouble(),
      bch: (json['bch'] as num?)?.toDouble(),
      bdt: (json['bdt'] as num?)?.toDouble(),
      bhd: (json['bhd'] as num?)?.toDouble(),
      bmd: (json['bmd'] as num?)?.toDouble(),
      bnb: (json['bnb'] as num?)?.toDouble(),
      brl: (json['brl'] as num?)?.toDouble(),
      btc: (json['btc'] as num?)?.toDouble(),
      cad: (json['cad'] as num?)?.toDouble(),
      chf: (json['chf'] as num?)?.toDouble(),
      clp: (json['clp'] as num?)?.toDouble(),
      cny: (json['cny'] as num?)?.toDouble(),
      czk: (json['czk'] as num?)?.toDouble(),
      dkk: (json['dkk'] as num?)?.toDouble(),
      dot: (json['dot'] as num?)?.toDouble(),
      eos: (json['eos'] as num?)?.toDouble(),
      eth: (json['eth'] as num?)?.toDouble(),
      eur: (json['eur'] as num?)?.toDouble(),
      gbp: (json['gbp'] as num?)?.toDouble(),
      hkd: (json['hkd'] as num?)?.toDouble(),
      huf: (json['huf'] as num?)?.toDouble(),
      idr: (json['idr'] as num?)?.toDouble(),
      ils: (json['ils'] as num?)?.toDouble(),
      inr: (json['inr'] as num?)?.toDouble(),
      jpy: (json['jpy'] as num?)?.toDouble(),
      krw: (json['krw'] as num?)?.toDouble(),
      kwd: (json['kwd'] as num?)?.toDouble(),
      lkr: (json['lkr'] as num?)?.toDouble(),
      ltc: (json['ltc'] as num?)?.toDouble(),
      mmk: (json['mmk'] as num?)?.toDouble(),
      mxn: (json['mxn'] as num?)?.toDouble(),
      myr: (json['myr'] as num?)?.toDouble(),
      ngn: (json['ngn'] as num?)?.toDouble(),
      nok: (json['nok'] as num?)?.toDouble(),
      nzd: (json['nzd'] as num?)?.toDouble(),
      php: (json['php'] as num?)?.toDouble(),
      pkr: (json['pkr'] as num?)?.toDouble(),
      pln: (json['pln'] as num?)?.toDouble(),
      rub: (json['rub'] as num?)?.toDouble(),
      sar: (json['sar'] as num?)?.toDouble(),
      sek: (json['sek'] as num?)?.toDouble(),
      sgd: (json['sgd'] as num?)?.toDouble(),
      thb: (json['thb'] as num?)?.toDouble(),
      tTry: (json['tTry'] as num?)?.toDouble(),
      twd: (json['twd'] as num?)?.toDouble(),
      uah: (json['uah'] as num?)?.toDouble(),
      usd: (json['usd'] as num?)?.toDouble(),
      vef: (json['vef'] as num?)?.toDouble(),
      vnd: (json['vnd'] as num?)?.toDouble(),
      xag: (json['xag'] as num?)?.toDouble(),
      xau: (json['xau'] as num?)?.toDouble(),
      xdr: (json['xdr'] as num?)?.toDouble(),
      xlm: (json['xlm'] as num?)?.toDouble(),
      xrp: (json['xrp'] as num?)?.toDouble(),
      yfi: (json['yfi'] as num?)?.toDouble(),
      zar: (json['zar'] as num?)?.toDouble(),
      bits: (json['bits'] as num?)?.toDouble(),
      link: (json['link'] as num?)?.toDouble(),
      sats: (json['sats'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$AthToJson(Ath instance) => <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

AthChangePercentage _$AthChangePercentageFromJson(Map<String, dynamic> json) =>
    AthChangePercentage(
      aed: (json['aed'] as num?)?.toDouble(),
      ars: (json['ars'] as num?)?.toDouble(),
      aud: (json['aud'] as num?)?.toDouble(),
      bch: (json['bch'] as num?)?.toDouble(),
      bdt: (json['bdt'] as num?)?.toDouble(),
      bhd: (json['bhd'] as num?)?.toDouble(),
      bmd: (json['bmd'] as num?)?.toDouble(),
      bnb: (json['bnb'] as num?)?.toDouble(),
      brl: (json['brl'] as num?)?.toDouble(),
      btc: (json['btc'] as num?)?.toDouble(),
      cad: (json['cad'] as num?)?.toDouble(),
      chf: (json['chf'] as num?)?.toDouble(),
      clp: (json['clp'] as num?)?.toDouble(),
      cny: (json['cny'] as num?)?.toDouble(),
      czk: (json['czk'] as num?)?.toDouble(),
      dkk: (json['dkk'] as num?)?.toDouble(),
      dot: (json['dot'] as num?)?.toDouble(),
      eos: (json['eos'] as num?)?.toDouble(),
      eth: (json['eth'] as num?)?.toDouble(),
      eur: (json['eur'] as num?)?.toDouble(),
      gbp: (json['gbp'] as num?)?.toDouble(),
      hkd: (json['hkd'] as num?)?.toDouble(),
      huf: (json['huf'] as num?)?.toDouble(),
      idr: (json['idr'] as num?)?.toDouble(),
      ils: (json['ils'] as num?)?.toDouble(),
      inr: (json['inr'] as num?)?.toDouble(),
      jpy: (json['jpy'] as num?)?.toDouble(),
      krw: (json['krw'] as num?)?.toDouble(),
      kwd: (json['kwd'] as num?)?.toDouble(),
      lkr: (json['lkr'] as num?)?.toDouble(),
      ltc: (json['ltc'] as num?)?.toDouble(),
      mmk: (json['mmk'] as num?)?.toDouble(),
      mxn: (json['mxn'] as num?)?.toDouble(),
      myr: (json['myr'] as num?)?.toDouble(),
      ngn: (json['ngn'] as num?)?.toDouble(),
      nok: (json['nok'] as num?)?.toDouble(),
      nzd: (json['nzd'] as num?)?.toDouble(),
      php: (json['php'] as num?)?.toDouble(),
      pkr: (json['pkr'] as num?)?.toDouble(),
      pln: (json['pln'] as num?)?.toDouble(),
      rub: (json['rub'] as num?)?.toDouble(),
      sar: (json['sar'] as num?)?.toDouble(),
      sek: (json['sek'] as num?)?.toDouble(),
      sgd: (json['sgd'] as num?)?.toDouble(),
      thb: (json['thb'] as num?)?.toDouble(),
      tTry: (json['tTry'] as num?)?.toDouble(),
      twd: (json['twd'] as num?)?.toDouble(),
      uah: (json['uah'] as num?)?.toDouble(),
      usd: (json['usd'] as num?)?.toDouble(),
      vef: (json['vef'] as num?)?.toDouble(),
      vnd: (json['vnd'] as num?)?.toDouble(),
      xag: (json['xag'] as num?)?.toDouble(),
      xau: (json['xau'] as num?)?.toDouble(),
      xdr: (json['xdr'] as num?)?.toDouble(),
      xlm: (json['xlm'] as num?)?.toDouble(),
      xrp: (json['xrp'] as num?)?.toDouble(),
      yfi: (json['yfi'] as num?)?.toDouble(),
      zar: (json['zar'] as num?)?.toDouble(),
      bits: (json['bits'] as num?)?.toDouble(),
      link: (json['link'] as num?)?.toDouble(),
      sats: (json['sats'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$AthChangePercentageToJson(
        AthChangePercentage instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

AthDate _$AthDateFromJson(Map<String, dynamic> json) => AthDate(
      aed: json['aed'] as String,
      ars: json['ars'] as String,
      aud: json['aud'] as String,
      bch: json['bch'] as String,
      bdt: json['bdt'] as String,
      bhd: json['bhd'] as String,
      bmd: json['bmd'] as String,
      bnb: json['bnb'] as String,
      brl: json['brl'] as String,
      btc: json['btc'] as String,
      cad: json['cad'] as String,
      chf: json['chf'] as String,
      clp: json['clp'] as String,
      cny: json['cny'] as String,
      czk: json['czk'] as String,
      dkk: json['dkk'] as String,
      dot: json['dot'] as String,
      eos: json['eos'] as String,
      eth: json['eth'] as String,
      eur: json['eur'] as String,
      gbp: json['gbp'] as String,
      hkd: json['hkd'] as String,
      huf: json['huf'] as String,
      idr: json['idr'] as String,
      ils: json['ils'] as String,
      inr: json['inr'] as String,
      jpy: json['jpy'] as String,
      krw: json['krw'] as String,
      kwd: json['kwd'] as String,
      lkr: json['lkr'] as String,
      ltc: json['ltc'] as String,
      mmk: json['mmk'] as String,
      mxn: json['mxn'] as String,
      myr: json['myr'] as String,
      ngn: json['ngn'] as String,
      nok: json['nok'] as String,
      nzd: json['nzd'] as String,
      php: json['php'] as String,
      pkr: json['pkr'] as String,
      pln: json['pln'] as String,
      rub: json['rub'] as String,
      sar: json['sar'] as String,
      sek: json['sek'] as String,
      sgd: json['sgd'] as String,
      thb: json['thb'] as String,
      tTry: json['tTry'] as String,
      twd: json['twd'] as String,
      uah: json['uah'] as String,
      usd: json['usd'] as String,
      vef: json['vef'] as String,
      vnd: json['vnd'] as String,
      xag: json['xag'] as String,
      xau: json['xau'] as String,
      xdr: json['xdr'] as String,
      xlm: json['xlm'] as String,
      xrp: json['xrp'] as String,
      yfi: json['yfi'] as String,
      zar: json['zar'] as String,
      bits: json['bits'] as String,
      link: json['link'] as String,
      sats: json['sats'] as String,
    );

Map<String, dynamic> _$AthDateToJson(AthDate instance) => <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

Atl _$AtlFromJson(Map<String, dynamic> json) => Atl(
      aed: (json['aed'] as num?)?.toDouble(),
      ars: (json['ars'] as num?)?.toDouble(),
      aud: (json['aud'] as num?)?.toDouble(),
      bch: (json['bch'] as num?)?.toDouble(),
      bdt: (json['bdt'] as num?)?.toDouble(),
      bhd: (json['bhd'] as num?)?.toDouble(),
      bmd: (json['bmd'] as num?)?.toDouble(),
      bnb: (json['bnb'] as num?)?.toDouble(),
      brl: (json['brl'] as num?)?.toDouble(),
      btc: (json['btc'] as num?)?.toDouble(),
      cad: (json['cad'] as num?)?.toDouble(),
      chf: (json['chf'] as num?)?.toDouble(),
      clp: (json['clp'] as num?)?.toDouble(),
      cny: (json['cny'] as num?)?.toDouble(),
      czk: (json['czk'] as num?)?.toDouble(),
      dkk: (json['dkk'] as num?)?.toDouble(),
      dot: (json['dot'] as num?)?.toDouble(),
      eos: (json['eos'] as num?)?.toDouble(),
      eth: (json['eth'] as num?)?.toDouble(),
      eur: (json['eur'] as num?)?.toDouble(),
      gbp: (json['gbp'] as num?)?.toDouble(),
      hkd: (json['hkd'] as num?)?.toDouble(),
      huf: (json['huf'] as num?)?.toDouble(),
      idr: (json['idr'] as num?)?.toDouble(),
      ils: (json['ils'] as num?)?.toDouble(),
      inr: (json['inr'] as num?)?.toDouble(),
      jpy: (json['jpy'] as num?)?.toDouble(),
      krw: (json['krw'] as num?)?.toDouble(),
      kwd: (json['kwd'] as num?)?.toDouble(),
      lkr: (json['lkr'] as num?)?.toDouble(),
      ltc: (json['ltc'] as num?)?.toDouble(),
      mmk: (json['mmk'] as num?)?.toDouble(),
      mxn: (json['mxn'] as num?)?.toDouble(),
      myr: (json['myr'] as num?)?.toDouble(),
      ngn: (json['ngn'] as num?)?.toDouble(),
      nok: (json['nok'] as num?)?.toDouble(),
      nzd: (json['nzd'] as num?)?.toDouble(),
      php: (json['php'] as num?)?.toDouble(),
      pkr: (json['pkr'] as num?)?.toDouble(),
      pln: (json['pln'] as num?)?.toDouble(),
      rub: (json['rub'] as num?)?.toDouble(),
      sar: (json['sar'] as num?)?.toDouble(),
      sek: (json['sek'] as num?)?.toDouble(),
      sgd: (json['sgd'] as num?)?.toDouble(),
      thb: (json['thb'] as num?)?.toDouble(),
      tTry: (json['tTry'] as num?)?.toDouble(),
      twd: (json['twd'] as num?)?.toDouble(),
      uah: (json['uah'] as num?)?.toDouble(),
      usd: (json['usd'] as num?)?.toDouble(),
      vef: (json['vef'] as num?)?.toDouble(),
      vnd: (json['vnd'] as num?)?.toDouble(),
      xag: (json['xag'] as num?)?.toDouble(),
      xau: (json['xau'] as num?)?.toDouble(),
      xdr: (json['xdr'] as num?)?.toDouble(),
      xlm: (json['xlm'] as num?)?.toDouble(),
      xrp: (json['xrp'] as num?)?.toDouble(),
      yfi: (json['yfi'] as num?)?.toDouble(),
      zar: (json['zar'] as num?)?.toDouble(),
      bits: (json['bits'] as num?)?.toDouble(),
      link: (json['link'] as num?)?.toDouble(),
      sats: (json['sats'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$AtlToJson(Atl instance) => <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

AtlChangePercentage _$AtlChangePercentageFromJson(Map<String, dynamic> json) =>
    AtlChangePercentage(
      aed: (json['aed'] as num?)?.toDouble(),
      ars: (json['ars'] as num?)?.toDouble(),
      aud: (json['aud'] as num?)?.toDouble(),
      bch: (json['bch'] as num?)?.toDouble(),
      bdt: (json['bdt'] as num?)?.toDouble(),
      bhd: (json['bhd'] as num?)?.toDouble(),
      bmd: (json['bmd'] as num?)?.toDouble(),
      bnb: (json['bnb'] as num?)?.toDouble(),
      brl: (json['brl'] as num?)?.toDouble(),
      btc: (json['btc'] as num?)?.toDouble(),
      cad: (json['cad'] as num?)?.toDouble(),
      chf: (json['chf'] as num?)?.toDouble(),
      clp: (json['clp'] as num?)?.toDouble(),
      cny: (json['cny'] as num?)?.toDouble(),
      czk: (json['czk'] as num?)?.toDouble(),
      dkk: (json['dkk'] as num?)?.toDouble(),
      dot: (json['dot'] as num?)?.toDouble(),
      eos: (json['eos'] as num?)?.toDouble(),
      eth: (json['eth'] as num?)?.toDouble(),
      eur: (json['eur'] as num?)?.toDouble(),
      gbp: (json['gbp'] as num?)?.toDouble(),
      hkd: (json['hkd'] as num?)?.toDouble(),
      huf: (json['huf'] as num?)?.toDouble(),
      idr: (json['idr'] as num?)?.toDouble(),
      ils: (json['ils'] as num?)?.toDouble(),
      inr: (json['inr'] as num?)?.toDouble(),
      jpy: (json['jpy'] as num?)?.toDouble(),
      krw: (json['krw'] as num?)?.toDouble(),
      kwd: (json['kwd'] as num?)?.toDouble(),
      lkr: (json['lkr'] as num?)?.toDouble(),
      ltc: (json['ltc'] as num?)?.toDouble(),
      mmk: (json['mmk'] as num?)?.toDouble(),
      mxn: (json['mxn'] as num?)?.toDouble(),
      myr: (json['myr'] as num?)?.toDouble(),
      ngn: (json['ngn'] as num?)?.toDouble(),
      nok: (json['nok'] as num?)?.toDouble(),
      nzd: (json['nzd'] as num?)?.toDouble(),
      php: (json['php'] as num?)?.toDouble(),
      pkr: (json['pkr'] as num?)?.toDouble(),
      pln: (json['pln'] as num?)?.toDouble(),
      rub: (json['rub'] as num?)?.toDouble(),
      sar: (json['sar'] as num?)?.toDouble(),
      sek: (json['sek'] as num?)?.toDouble(),
      sgd: (json['sgd'] as num?)?.toDouble(),
      thb: (json['thb'] as num?)?.toDouble(),
      tTry: (json['tTry'] as num?)?.toDouble(),
      twd: (json['twd'] as num?)?.toDouble(),
      uah: (json['uah'] as num?)?.toDouble(),
      usd: (json['usd'] as num?)?.toDouble(),
      vef: (json['vef'] as num?)?.toDouble(),
      vnd: (json['vnd'] as num?)?.toDouble(),
      xag: (json['xag'] as num?)?.toDouble(),
      xau: (json['xau'] as num?)?.toDouble(),
      xdr: (json['xdr'] as num?)?.toDouble(),
      xlm: (json['xlm'] as num?)?.toDouble(),
      xrp: (json['xrp'] as num?)?.toDouble(),
      yfi: (json['yfi'] as num?)?.toDouble(),
      zar: (json['zar'] as num?)?.toDouble(),
      bits: (json['bits'] as num?)?.toDouble(),
      link: (json['link'] as num?)?.toDouble(),
      sats: (json['sats'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$AtlChangePercentageToJson(
        AtlChangePercentage instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

AtlDate _$AtlDateFromJson(Map<String, dynamic> json) => AtlDate(
      aed: json['aed'] as String,
      ars: json['ars'] as String,
      aud: json['aud'] as String,
      bch: json['bch'] as String,
      bdt: json['bdt'] as String,
      bhd: json['bhd'] as String,
      bmd: json['bmd'] as String,
      bnb: json['bnb'] as String,
      brl: json['brl'] as String,
      btc: json['btc'] as String,
      cad: json['cad'] as String,
      chf: json['chf'] as String,
      clp: json['clp'] as String,
      cny: json['cny'] as String,
      czk: json['czk'] as String,
      dkk: json['dkk'] as String,
      dot: json['dot'] as String,
      eos: json['eos'] as String,
      eth: json['eth'] as String,
      eur: json['eur'] as String,
      gbp: json['gbp'] as String,
      hkd: json['hkd'] as String,
      huf: json['huf'] as String,
      idr: json['idr'] as String,
      ils: json['ils'] as String,
      inr: json['inr'] as String,
      jpy: json['jpy'] as String,
      krw: json['krw'] as String,
      kwd: json['kwd'] as String,
      lkr: json['lkr'] as String,
      ltc: json['ltc'] as String,
      mmk: json['mmk'] as String,
      mxn: json['mxn'] as String,
      myr: json['myr'] as String,
      ngn: json['ngn'] as String,
      nok: json['nok'] as String,
      nzd: json['nzd'] as String,
      php: json['php'] as String,
      pkr: json['pkr'] as String,
      pln: json['pln'] as String,
      rub: json['rub'] as String,
      sar: json['sar'] as String,
      sek: json['sek'] as String,
      sgd: json['sgd'] as String,
      thb: json['thb'] as String,
      tTry: json['tTry'] as String,
      twd: json['twd'] as String,
      uah: json['uah'] as String,
      usd: json['usd'] as String,
      vef: json['vef'] as String,
      vnd: json['vnd'] as String,
      xag: json['xag'] as String,
      xau: json['xau'] as String,
      xdr: json['xdr'] as String,
      xlm: json['xlm'] as String,
      xrp: json['xrp'] as String,
      yfi: json['yfi'] as String,
      zar: json['zar'] as String,
      bits: json['bits'] as String,
      link: json['link'] as String,
      sats: json['sats'] as String,
    );

Map<String, dynamic> _$AtlDateToJson(AtlDate instance) => <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

MarketCap _$MarketCapFromJson(Map<String, dynamic> json) => MarketCap(
      aed: (json['aed'] as num?)?.toDouble(),
      ars: (json['ars'] as num?)?.toDouble(),
      aud: (json['aud'] as num?)?.toDouble(),
      bch: (json['bch'] as num?)?.toDouble(),
      bdt: (json['bdt'] as num?)?.toDouble(),
      bhd: (json['bhd'] as num?)?.toDouble(),
      bmd: (json['bmd'] as num?)?.toDouble(),
      bnb: (json['bnb'] as num?)?.toDouble(),
      brl: (json['brl'] as num?)?.toDouble(),
      btc: (json['btc'] as num?)?.toDouble(),
      cad: (json['cad'] as num?)?.toDouble(),
      chf: (json['chf'] as num?)?.toDouble(),
      clp: (json['clp'] as num?)?.toDouble(),
      cny: (json['cny'] as num?)?.toDouble(),
      czk: (json['czk'] as num?)?.toDouble(),
      dkk: (json['dkk'] as num?)?.toDouble(),
      dot: (json['dot'] as num?)?.toDouble(),
      eos: (json['eos'] as num?)?.toDouble(),
      eth: (json['eth'] as num?)?.toDouble(),
      eur: (json['eur'] as num?)?.toDouble(),
      gbp: (json['gbp'] as num?)?.toDouble(),
      hkd: (json['hkd'] as num?)?.toDouble(),
      huf: (json['huf'] as num?)?.toDouble(),
      idr: (json['idr'] as num?)?.toDouble(),
      ils: (json['ils'] as num?)?.toDouble(),
      inr: (json['inr'] as num?)?.toDouble(),
      jpy: (json['jpy'] as num?)?.toDouble(),
      krw: (json['krw'] as num?)?.toDouble(),
      kwd: (json['kwd'] as num?)?.toDouble(),
      lkr: (json['lkr'] as num?)?.toDouble(),
      ltc: (json['ltc'] as num?)?.toDouble(),
      mmk: (json['mmk'] as num?)?.toDouble(),
      mxn: (json['mxn'] as num?)?.toDouble(),
      myr: (json['myr'] as num?)?.toDouble(),
      ngn: (json['ngn'] as num?)?.toDouble(),
      nok: (json['nok'] as num?)?.toDouble(),
      nzd: (json['nzd'] as num?)?.toDouble(),
      php: (json['php'] as num?)?.toDouble(),
      pkr: (json['pkr'] as num?)?.toDouble(),
      pln: (json['pln'] as num?)?.toDouble(),
      rub: (json['rub'] as num?)?.toDouble(),
      sar: (json['sar'] as num?)?.toDouble(),
      sek: (json['sek'] as num?)?.toDouble(),
      sgd: (json['sgd'] as num?)?.toDouble(),
      thb: (json['thb'] as num?)?.toDouble(),
      tTry: (json['tTry'] as num?)?.toDouble(),
      twd: (json['twd'] as num?)?.toDouble(),
      uah: (json['uah'] as num?)?.toDouble(),
      usd: (json['usd'] as num?)?.toDouble(),
      vef: (json['vef'] as num?)?.toDouble(),
      vnd: (json['vnd'] as num?)?.toDouble(),
      xag: (json['xag'] as num?)?.toDouble(),
      xau: (json['xau'] as num?)?.toDouble(),
      xdr: (json['xdr'] as num?)?.toDouble(),
      xlm: (json['xlm'] as num?)?.toDouble(),
      xrp: (json['xrp'] as num?)?.toDouble(),
      yfi: (json['yfi'] as num?)?.toDouble(),
      zar: (json['zar'] as num?)?.toDouble(),
      bits: (json['bits'] as num?)?.toDouble(),
      link: (json['link'] as num?)?.toDouble(),
      sats: (json['sats'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$MarketCapToJson(MarketCap instance) => <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

FullyDilutedValuation _$FullyDilutedValuationFromJson(
        Map<String, dynamic> json) =>
    FullyDilutedValuation(
      aed: json['aed'] as int?,
      ars: json['ars'] as int?,
      aud: json['aud'] as int?,
      bch: json['bch'] as int?,
      bdt: json['bdt'] as int?,
      bhd: json['bhd'] as int?,
      bmd: json['bmd'] as int?,
      bnb: json['bnb'] as int?,
      brl: json['brl'] as int?,
      btc: json['btc'] as int?,
      cad: json['cad'] as int?,
      chf: json['chf'] as int?,
      clp: json['clp'] as int?,
      cny: json['cny'] as int?,
      czk: json['czk'] as int?,
      dkk: json['dkk'] as int?,
      dot: json['dot'] as int?,
      eos: json['eos'] as int?,
      eth: json['eth'] as int?,
      eur: json['eur'] as int?,
      gbp: json['gbp'] as int?,
      hkd: json['hkd'] as int?,
      huf: json['huf'] as int?,
      idr: json['idr'] as int?,
      ils: json['ils'] as int?,
      inr: json['inr'] as int?,
      jpy: json['jpy'] as int?,
      krw: json['krw'] as int?,
      kwd: json['kwd'] as int?,
      lkr: json['lkr'] as int?,
      ltc: json['ltc'] as int?,
      mmk: json['mmk'] as int?,
      mxn: json['mxn'] as int?,
      myr: json['myr'] as int?,
      ngn: json['ngn'] as int?,
      nok: json['nok'] as int?,
      nzd: json['nzd'] as int?,
      php: json['php'] as int?,
      pkr: json['pkr'] as int?,
      pln: json['pln'] as int?,
      rub: json['rub'] as int?,
      sar: json['sar'] as int?,
      sek: json['sek'] as int?,
      sgd: json['sgd'] as int?,
      thb: json['thb'] as int?,
      tTry: json['tTry'] as int?,
      twd: json['twd'] as int?,
      uah: json['uah'] as int?,
      usd: json['usd'] as int?,
      vef: json['vef'] as int?,
      vnd: json['vnd'] as int?,
      xag: json['xag'] as int?,
      xau: json['xau'] as int?,
      xdr: json['xdr'] as int?,
      xlm: json['xlm'] as int?,
      xrp: json['xrp'] as int?,
      yfi: json['yfi'] as int?,
      zar: json['zar'] as int?,
      bits: json['bits'] as int?,
      link: json['link'] as int?,
      sats: json['sats'] as int?,
    );

Map<String, dynamic> _$FullyDilutedValuationToJson(
        FullyDilutedValuation instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

TotalVolume _$TotalVolumeFromJson(Map<String, dynamic> json) => TotalVolume(
      aed: json['aed'] as int?,
      ars: json['ars'] as int?,
      aud: json['aud'] as int?,
      bch: json['bch'] as int?,
      bdt: json['bdt'] as int?,
      bhd: json['bhd'] as int?,
      bmd: json['bmd'] as int?,
      bnb: json['bnb'] as int?,
      brl: json['brl'] as int?,
      btc: json['btc'] as int?,
      cad: json['cad'] as int?,
      chf: json['chf'] as int?,
      clp: json['clp'] as int?,
      cny: json['cny'] as int?,
      czk: json['czk'] as int?,
      dkk: json['dkk'] as int?,
      dot: json['dot'] as int?,
      eos: json['eos'] as int?,
      eth: json['eth'] as int?,
      eur: json['eur'] as int?,
      gbp: json['gbp'] as int?,
      hkd: json['hkd'] as int?,
      huf: json['huf'] as int?,
      idr: json['idr'] as int?,
      ils: json['ils'] as int?,
      inr: json['inr'] as int?,
      jpy: json['jpy'] as int?,
      krw: json['krw'] as int?,
      kwd: json['kwd'] as int?,
      lkr: json['lkr'] as int?,
      ltc: json['ltc'] as int?,
      mmk: json['mmk'] as int?,
      mxn: json['mxn'] as int?,
      myr: json['myr'] as int?,
      ngn: json['ngn'] as int?,
      nok: json['nok'] as int?,
      nzd: json['nzd'] as int?,
      php: json['php'] as int?,
      pkr: json['pkr'] as int?,
      pln: json['pln'] as int?,
      rub: json['rub'] as int?,
      sar: json['sar'] as int?,
      sek: json['sek'] as int?,
      sgd: json['sgd'] as int?,
      thb: json['thb'] as int?,
      tTry: json['tTry'] as int?,
      twd: json['twd'] as int?,
      uah: json['uah'] as int?,
      usd: json['usd'] as int?,
      vef: json['vef'] as int?,
      vnd: json['vnd'] as int?,
      xag: json['xag'] as int?,
      xau: json['xau'] as int?,
      xdr: json['xdr'] as int?,
      xlm: json['xlm'] as int?,
      xrp: json['xrp'] as int?,
      yfi: json['yfi'] as int?,
      zar: json['zar'] as int?,
      bits: json['bits'] as int?,
      link: json['link'] as int?,
      sats: json['sats'] as int?,
    );

Map<String, dynamic> _$TotalVolumeToJson(TotalVolume instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

High24h _$High24hFromJson(Map<String, dynamic> json) => High24h(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      tTry: (json['tTry'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      sats: (json['sats'] as num).toDouble(),
    );

Map<String, dynamic> _$High24hToJson(High24h instance) => <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

Low24h _$Low24hFromJson(Map<String, dynamic> json) => Low24h(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      tTry: (json['tTry'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      sats: (json['sats'] as num).toDouble(),
    );

Map<String, dynamic> _$Low24hToJson(Low24h instance) => <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

PriceChange24hInCurrency _$PriceChange24hInCurrencyFromJson(
        Map<String, dynamic> json) =>
    PriceChange24hInCurrency(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      tTry: (json['tTry'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      sats: (json['sats'] as num).toDouble(),
    );

Map<String, dynamic> _$PriceChange24hInCurrencyToJson(
        PriceChange24hInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

PriceChangePercentage1hInCurrency _$PriceChangePercentage1hInCurrencyFromJson(
        Map<String, dynamic> json) =>
    PriceChangePercentage1hInCurrency(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      tTry: (json['tTry'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      sats: (json['sats'] as num).toDouble(),
    );

Map<String, dynamic> _$PriceChangePercentage1hInCurrencyToJson(
        PriceChangePercentage1hInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

PriceChangePercentage24hInCurrency _$PriceChangePercentage24hInCurrencyFromJson(
        Map<String, dynamic> json) =>
    PriceChangePercentage24hInCurrency(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      tTry: (json['tTry'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      sats: (json['sats'] as num).toDouble(),
    );

Map<String, dynamic> _$PriceChangePercentage24hInCurrencyToJson(
        PriceChangePercentage24hInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

PriceChangePercentage7dInCurrency _$PriceChangePercentage7dInCurrencyFromJson(
        Map<String, dynamic> json) =>
    PriceChangePercentage7dInCurrency(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      tTry: (json['tTry'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      sats: (json['sats'] as num).toDouble(),
    );

Map<String, dynamic> _$PriceChangePercentage7dInCurrencyToJson(
        PriceChangePercentage7dInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

PriceChangePercentage14dInCurrency _$PriceChangePercentage14dInCurrencyFromJson(
        Map<String, dynamic> json) =>
    PriceChangePercentage14dInCurrency(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      tTry: (json['tTry'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      sats: (json['sats'] as num).toDouble(),
    );

Map<String, dynamic> _$PriceChangePercentage14dInCurrencyToJson(
        PriceChangePercentage14dInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

PriceChangePercentage30dInCurrency _$PriceChangePercentage30dInCurrencyFromJson(
        Map<String, dynamic> json) =>
    PriceChangePercentage30dInCurrency(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      tTry: (json['tTry'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      sats: (json['sats'] as num).toDouble(),
    );

Map<String, dynamic> _$PriceChangePercentage30dInCurrencyToJson(
        PriceChangePercentage30dInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

PriceChangePercentage60dInCurrency _$PriceChangePercentage60dInCurrencyFromJson(
        Map<String, dynamic> json) =>
    PriceChangePercentage60dInCurrency(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      tTry: (json['tTry'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      sats: (json['sats'] as num).toDouble(),
    );

Map<String, dynamic> _$PriceChangePercentage60dInCurrencyToJson(
        PriceChangePercentage60dInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'tTry': instance.tTry,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'sats': instance.sats,
    };

SparkLine7d _$SparkLine7dFromJson(Map<String, dynamic> json) => SparkLine7d(
      price: (json['price'] as List<dynamic>)
          .map((e) => (e as num).toDouble())
          .toList(),
    );

Map<String, dynamic> _$SparkLine7dToJson(SparkLine7d instance) =>
    <String, dynamic>{
      'price': instance.price,
    };
